version: 0.0
os: linux

files:
  - source: /src
    destination: /home/ec2-user/ecjackson/CodeDeploy/hospital_charges_app
    
permissions:
  - object: /home/ec2-user/ecjackson/CodeDeploy/hospital_charges_app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  - object: /home/ec2-user/ecjackson/CodeDeploy
    pattern: "hospital_charges_app"
    owner: ec2-user
    group: ec2-user
    type:
      - directory

hooks:
  ApplicationStop:
    - location: bin/application_stop.sh
      timeout: 15
      runas: ec2-user
  BeforeInstall:
    - location: bin/before_install.sh
      timeout: 120
      runas: ec2-user
  AfterInstall:
    - location: bin/after_install.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: bin/application_start.sh
      timeout: 120
      runas: ec2-user

